<?php

return array(
    'titles'            => array(
        'singular' => 'Dbdeploy Changelog',
        'plural'   => 'Dbdeploy Changelogs',
    ),
    'columns'           => array (
  'change_number' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dbdeploy_changelog',
    'COLUMN_NAME' => 'change_number',
    'COLUMN_POSITION' => 1,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => true,
    'PRIMARY_POSITION' => 1,
    'IDENTITY' => false,
  ),
  'delta_set' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dbdeploy_changelog',
    'COLUMN_NAME' => 'delta_set',
    'COLUMN_POSITION' => 2,
    'DATA_TYPE' => 'varchar',
    'GENERIC_TYPE' => 'text',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '32',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => true,
    'PRIMARY_POSITION' => 2,
    'IDENTITY' => false,
  ),
  'start_dt' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dbdeploy_changelog',
    'COLUMN_NAME' => 'start_dt',
    'COLUMN_POSITION' => 3,
    'DATA_TYPE' => 'timestamp',
    'GENERIC_TYPE' => 'timestamp',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 8,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'complete_dt' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dbdeploy_changelog',
    'COLUMN_NAME' => 'complete_dt',
    'COLUMN_POSITION' => 4,
    'DATA_TYPE' => 'timestamp',
    'GENERIC_TYPE' => 'timestamp',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 8,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'applied_by' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dbdeploy_changelog',
    'COLUMN_NAME' => 'applied_by',
    'COLUMN_POSITION' => 5,
    'DATA_TYPE' => 'varchar',
    'GENERIC_TYPE' => 'text',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '32',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'description' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dbdeploy_changelog',
    'COLUMN_NAME' => 'description',
    'COLUMN_POSITION' => 6,
    'DATA_TYPE' => 'text',
    'GENERIC_TYPE' => 'clob',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => -1,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
),
    'references'        => array (
),
    'uniqueConstraints' => array (
),
);
