<?php

return array(
    'titles'            => array(
        'singular' => 'Dewdrop Notification Subscription',
        'plural'   => 'Dewdrop Notification Subscriptions',
    ),
    'columns'           => array (
  'dewdrop_notification_subscription_id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'dewdrop_notification_subscription_id',
    'COLUMN_POSITION' => 1,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => true,
    'PRIMARY_POSITION' => 1,
    'IDENTITY' => true,
  ),
  'component' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'component',
    'COLUMN_POSITION' => 2,
    'DATA_TYPE' => 'varchar',
    'GENERIC_TYPE' => 'text',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '128',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'dewdrop_notification_frequency_id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'dewdrop_notification_frequency_id',
    'COLUMN_POSITION' => 3,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'when_added' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'when_added',
    'COLUMN_POSITION' => 4,
    'DATA_TYPE' => 'bool',
    'GENERIC_TYPE' => 'boolean',
    'DEFAULT' => 1,
    'NULLABLE' => false,
    'LENGTH' => 1,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'when_edited' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'when_edited',
    'COLUMN_POSITION' => 5,
    'DATA_TYPE' => 'bool',
    'GENERIC_TYPE' => 'boolean',
    'DEFAULT' => 1,
    'NULLABLE' => false,
    'LENGTH' => 1,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'preferred_time_of_day' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'preferred_time_of_day',
    'COLUMN_POSITION' => 6,
    'DATA_TYPE' => 'time',
    'GENERIC_TYPE' => 'time',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 8,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'preferred_day_of_week' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'preferred_day_of_week',
    'COLUMN_POSITION' => 7,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'date_created' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'date_created',
    'COLUMN_POSITION' => 8,
    'DATA_TYPE' => 'timestamp',
    'GENERIC_TYPE' => 'timestamp',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 8,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'date_updated' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'dewdrop_notification_subscriptions',
    'COLUMN_NAME' => 'date_updated',
    'COLUMN_POSITION' => 9,
    'DATA_TYPE' => 'timestamp',
    'GENERIC_TYPE' => 'timestamp',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 8,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
),
    'references'        => array (
  'dewdrop_notification_frequency_id' => 
  array (
    'table' => 'dewdrop_notification_frequencies',
    'column' => 'dewdrop_notification_frequency_id',
  ),
),
    'uniqueConstraints' => array (
),
);
