<?php

return array(
    'titles'            => array(
        'singular' => 'Environment Resource',
        'plural'   => 'Environment Resources',
    ),
    'columns'           => array (
  'environment_resource_id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'environment_resources',
    'COLUMN_NAME' => 'environment_resource_id',
    'COLUMN_POSITION' => 1,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => true,
    'PRIMARY_POSITION' => 1,
    'IDENTITY' => true,
  ),
  'environment_id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'environment_resources',
    'COLUMN_NAME' => 'environment_id',
    'COLUMN_POSITION' => 2,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'encrypted_key' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'environment_resources',
    'COLUMN_NAME' => 'encrypted_key',
    'COLUMN_POSITION' => 4,
    'DATA_TYPE' => 'text',
    'GENERIC_TYPE' => 'clob',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => -1,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'encrypted_contents' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'environment_resources',
    'COLUMN_NAME' => 'encrypted_contents',
    'COLUMN_POSITION' => 5,
    'DATA_TYPE' => 'text',
    'GENERIC_TYPE' => 'clob',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => -1,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'date_created' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'environment_resources',
    'COLUMN_NAME' => 'date_created',
    'COLUMN_POSITION' => 6,
    'DATA_TYPE' => 'timestamp',
    'GENERIC_TYPE' => 'timestamp',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 8,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'cipher' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'environment_resources',
    'COLUMN_NAME' => 'cipher',
    'COLUMN_POSITION' => 7,
    'DATA_TYPE' => 'varchar',
    'GENERIC_TYPE' => 'text',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '128',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'environment_resource_type_id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'environment_resources',
    'COLUMN_NAME' => 'environment_resource_type_id',
    'COLUMN_POSITION' => 8,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
),
    'references'        => array (
  'environment_id' => 
  array (
    'table' => 'environments',
    'column' => 'environment_id',
  ),
  'environment_resource_type_id' => 
  array (
    'table' => 'environment_resource_types',
    'column' => 'environment_resource_type_id',
  ),
),
    'uniqueConstraints' => array (
),
);
