<?php

return array(
    'titles'            => array(
        'singular' => 'Sign Up Request',
        'plural'   => 'Sign Up Requests',
    ),
    'columns'           => array (
  'sign_up_request_id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'sign_up_requests',
    'COLUMN_NAME' => 'sign_up_request_id',
    'COLUMN_POSITION' => 1,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => true,
    'PRIMARY_POSITION' => 1,
    'IDENTITY' => true,
  ),
  'email_address' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'sign_up_requests',
    'COLUMN_NAME' => 'email_address',
    'COLUMN_POSITION' => 2,
    'DATA_TYPE' => 'varchar',
    'GENERIC_TYPE' => 'text',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '255',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'authorized_email_domain_id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'sign_up_requests',
    'COLUMN_NAME' => 'authorized_email_domain_id',
    'COLUMN_POSITION' => 3,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'authorized_by_user_id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'sign_up_requests',
    'COLUMN_NAME' => 'authorized_by_user_id',
    'COLUMN_POSITION' => 4,
    'DATA_TYPE' => 'int4',
    'GENERIC_TYPE' => 'integer',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'authorization_code' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'sign_up_requests',
    'COLUMN_NAME' => 'authorization_code',
    'COLUMN_POSITION' => 5,
    'DATA_TYPE' => 'varchar',
    'GENERIC_TYPE' => 'text',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '32',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'date_created' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'sign_up_requests',
    'COLUMN_NAME' => 'date_created',
    'COLUMN_POSITION' => 6,
    'DATA_TYPE' => 'timestamp',
    'GENERIC_TYPE' => 'timestamp',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => 8,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
),
    'references'        => array (
  'authorized_email_domain_id' => 
  array (
    'table' => 'authorized_email_domains',
    'column' => 'authorized_email_domain_id',
  ),
  'authorized_by_user_id' => 
  array (
    'table' => 'users',
    'column' => 'user_id',
  ),
),
    'uniqueConstraints' => array (
),
);
